
package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.access.CategoryRestRepository;
import co.com.hyunseda.market.access.ProductRestRepository;
import co.com.hyunseda.market.access.UserRestRepository;
import co.com.hyunseda.market.domain.ERole;
import co.com.hyunseda.market.domain.Rol;
import co.com.hyunseda.market.domain.User;
import co.com.hyunseda.market.service.CarritoService;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.UserService;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.xml.transform.Source;

/**
 *
 * @author ACER
 */
public class GUILogin extends javax.swing.JFrame {
    
     ProductService productService;
     CategoryService categoryService;
     CarritoService carritoService;
     UserService  userService;

    /**
     * Creates new form GUIUserMen
     */
    public GUILogin() {
        initComponents();
        //Inicializar variables
        this.productService  = new ProductService(new ProductRestRepository());
        this.categoryService = new CategoryService(new CategoryRestRepository());
        this.userService = new UserService(new UserRestRepository());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cbxViewPassword = new javax.swing.JCheckBox();
        btnSalir = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("BIENVENIDO A HYUNSEDA");
        jLabel3.setToolTipText("");
        jPanel4.add(jLabel3);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        cbxViewPassword.setText("Mostrar contraseña");
        cbxViewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxViewPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(btnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxViewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxViewPassword)
                .addGap(4, 4, 4)
                .addComponent(btnIngresar)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(txtUser.getText().equals("") || txtPassword.getPassword().length == 0)
        {
            JOptionPane.showMessageDialog(txtUser, "Debe digitar usuario o contraseña","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        String user = txtUser.getText();
        char[] passwordArray = txtPassword.getPassword();
        String password = new String(passwordArray);
        User loginUser = new User(user,password);
        boolean isLogin = userService.log_in(loginUser);
        
        if(isLogin)
        {
            //Obtener el usuario que ha ingresado
            User objUser = userService.getUserByUserName(user); /**<!Recuperar la clase usuario con el userName*/
            
            List<Rol> rolesUser = new ArrayList<>();
            objUser.getRoles().forEach(role -> rolesUser.add(role));//Recuperar los roles del HashSet y pasarlos a un arrayList
            
            
            if(rolesUser.size() < 2)
            {
                if(rolesUser.get(0).getName().name().equals("INVITED"))
                 {
                     this.dispose();
                     GUIStoreProducts objStoreProducts = new GUIStoreProducts(this, isLogin, productService, carritoService, objUser, rolesUser);
                     objStoreProducts.setVisible(true);
                 }else
                    {
                     this.dispose();
                     GUIMainMenu objMainMenu = new GUIMainMenu(objUser, rolesUser);
                     objMainMenu.setVisible(true);
                    }
            }else{
                if(rolesUser.get(0).getName().name().equals("INVITED") || rolesUser.get(1).getName().name().equals("INVITED"))
                {
                     this.dispose();
                     GUIStoreProducts objStoreProducts = new GUIStoreProducts(this, isLogin, productService, carritoService, objUser, rolesUser);
                     objStoreProducts.setVisible(true);
                }else
                {
                    this.dispose();
                     GUIMainMenu objMainMenu = new GUIMainMenu(objUser, rolesUser);
                     objMainMenu.setVisible(true);
                }

            }
  
        }else
        {
            JOptionPane.showMessageDialog(null, "Usuario no ha podido iniciar sesión", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void cbxViewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxViewPasswordActionPerformed
       if(cbxViewPassword.isSelected()){
           txtPassword.setEchoChar((char)0);
       }else{
           txtPassword.setEchoChar('*');
       }
    }//GEN-LAST:event_cbxViewPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbxViewPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
